name: CI

on:
  push:
  release:
    types: [published]

jobs:

  # run build in prod mode
  build-test:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.10.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.10.x
    - name: Install dependencies
      run: npm install
    - name: Build app in prod mode
      run: npm run build-prod
    - name: Build docker image
      run: make build-app-image

  # publish only on release
  publish:
    name: Publish to Dockerhub
    needs: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: checkout source
        uses: actions/checkout@v1
        with:
          fetch-depth: 50
      - name: build and publish image
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          make publish-app-image
